language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - chmod +x ./mvnw
script:
  - mvn clean package -DskipTests=true docker:build
  - docker login -u="edidada" -p="5Edidada"
  - docker push edidada/zipkin-server
notifications:
  email:
    recipients:
    - sandisks555@gmail.com
    on_success: always # default: change never
    on_failure: always # default: always